"use client"

import React, { createContext, useContext, useState, useEffect } from 'react';

const en = {
    "Brand Name": "Friends Farm",
    "Shop Now": "Shop Now",
    "Categories": "Categories",
    "Explore Our Sections": "Explore Our Sections",
    "All": "All",
    "Featured Products": "Featured Products",
    "All Products": "All Products",
    "Fast Delivery": "Fast Delivery",
    "Home Raised": "Home Raised",
    "High Quality": "High Quality",
    "Add to Cart": "Add to Cart",
    "EGP": "EGP",
    "Login": "Login",
    "Admin": "Dashboard",
    "Loading Farm": "Loading Farm",
    "Welcome Message": "Welcome to Friends Farm",
    "Hero Slogan": "Best selection of fresh poultry - fast delivery to your door",
    "Cart": "Shopping Cart",
    "Empty Cart": "Your cart is empty.",
    "Total": "Total",
    "Checkout": "Checkout",
    "Remove": "Remove",
    "Products": "Products",
    "Continue with Google": "Continue with Google",
    "Secure Login Message": "Securely connect via Google to manage your farm orders",
    "All Rights Reserved": "All Rights Reserved",
    "Developed by": "Developed by Abdallah Sayed",
    "Fresh from the farm": "Fresh from our farm directly to you.",
    "Delivery Policy": "Delivery Policy",
    "About Farm": "About Farm",
    "Within 24 hours": "Within 24 hours",
    "No hormones or additives": "No hormones or additives",
    "Slaughtered according to Sharia": "Slaughtered according to Sharia",
    "Fresh chicken and birds of the highest quality": "Fresh chicken and birds of the highest quality",
    "Best selection of fresh poultry": "Best selection of fresh poultry - fast delivery to your door",
    "Email": "Email",
    "Password": "Password",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    "Register": "Register",
    "Don't have an account?": "Don't have an account?",
    "Already have an account?": "Already have an account?",
    "Forgot Password?": "Forgot Password?",
    "Full Name": "Full Name",
    "Create Account": "Create Account",
    "Logout": "Logout",
    "Dashboard Summary": "Snapshot of your farm's performance",
    "Total Revenue": "Total Revenue",
    "Monthly Revenue": "Monthly Revenue",
    "Pending Orders": "Pending Orders",
    "Total Customers": "Total Customers",
    "Recent Orders": "Recent Orders",
    "Top Performing Products": "Top Performing Products",
    "Lifetime Earnings": "Lifetime Earnings",
    "Last 30 Days": "Last 30 Days",
    "Awaiting Delivery": "Awaiting Delivery",
    "Active Accounts": "Active Accounts",
    "Guest": "Guest",
    "Expenses": "Expenses",
    "Overview": "Overview",
    "Orders": "Orders",
    "Users": "Users",
    "Settings": "Settings",
    "Category Name": "Category Name",
    "Category Name (Arabic)": "Category Name (Arabic)",
    "Category Image": "Category Image",
    "Add New Category": "Add New Category",
    "Manage product sections": "Manage product sections",
    "Date": "Date",
    "Action": "Action",
    "Name (EN)": "Name (EN)",
    "Name (AR)": "Name (AR)",
    "Image": "Image",
    "Are you sure?": "Are you sure?",
    "This action cannot be undone.": "This action cannot be undone.",
    "Cancel": "Cancel",
    "Continue": "Continue",
    "Successfully deleted": "Successfully deleted",
    "Something went wrong": "Something went wrong",
    "Create": "Create",
    "Save Changes": "Save Changes",
    "Price": "Price",
    "Category": "Category",
    "Stock": "Stock",
    "Featured": "Featured",
    "Active": "Active",
    "items": "items",
    "Loading...": "Loading...",
    "Edit Product": "Edit Product",
    "Add New Product": "Add New Product",
    "Product Name": "Product Name",
    "Product Name (Arabic)": "Product Name (Arabic)",
    "Description": "Description",
    "Description (Arabic)": "Description (Arabic)",
    "Product Image": "Product Image",
    "Featured Product": "Featured Product",
    "Featured Description": "This product will appear on the home page",
    "Available Product": "Available Product",
    "Available Description": "This product will be visible in the store",
    "Order ID": "Order ID",
    "Customer": "Customer",
    "Phone": "Phone",
    "Address": "Address",
    "Status": "Status",
    "Total Price": "Total Price",
    "Manage Orders": "Manage Orders",
    "Manage Users": "Manage Users",
    "Name": "Name",
    "Role": "Role",
    "Actions": "Actions",
    "My Account": "My Account",
    "Please login to checkout": "Please login to checkout",
    "Order placed successfully!": "Order placed successfully!",
    "Account created successfully!": "Account created successfully!",
    "Account created! Please login.": "Account created! Please login.",
    "Registration failed": "Registration failed",
    "Filters": "Filters",
    "All Categories": "All Categories",
    "Sort By": "Sort By",
    "Default": "Default",
    "Price: Low to High": "Price: Low to High",
    "Price: High to Low": "Price: High to Low",
    "Newest First": "Newest First",
    "Clear": "Clear",
    "No products found": "No products found",
    "Customer Reviews": "Customer Reviews",
    "What Our Customers Say": "What Our Customers Say",
    "Verified Customer": "Verified Customer",
    "Special Offers": "Special Offers",
    "Don't Miss Out!": "Don't Miss Out!",
    "OFF": "OFF",
    "Top Rated": "Top Rated",
    "Our Picks For You": "Our Picks For You",
    "Admin Dashboard": "Admin Dashboard",
    "Sales Overview": "Sales Overview",
    "Monthly Revenue Tracking": "Monthly Revenue Tracking",
    "Finance Hub": "Finance Hub",
    "Net Profit vs Expenses": "Net Profit vs Expenses",
    "Net Profit": "Net Profit",
    "Offers": "Offers",
    "Manage Offers": "Manage Offers",
    "Add New Offer": "Add New Offer",
    "Offer Title": "Offer Title",
    "Discount Percentage": "Discount Percentage",
    "Offer Price": "Offer Price",
    "Original Price": "Original Price",
    "Testimonials": "Testimonials",
    "Manage Testimonials": "Manage Testimonials",
    "Approved": "Approved",
    "Pending Approval": "Pending Approval",
    "Approve": "Approve",
    "Reject": "Reject",
    "Error": "Error",
    "Columns": "Columns",
    "No results.": "No results.",
    "Previous": "Previous",
    "Next": "Next",
    "Filter...": "Filter...",
    "Select All": "Select All",
    "name": "Name",
    "name_ar": "Name (Ar)",
    "price": "Price",
    "category": "Category",
    "createdAt": "Created At",
    "isFeatured": "Featured",
    "isArchived": "Archived",
    "Area / Region": "Area / Region",
    "Street Name": "Street Name",
    "Building No": "Building No",
    "Floor No": "Floor No",
    "Apartment No": "Apartment No",
    "Location Added ✓": "Location Added ✓",
    "Share My Current Location": "Share My Current Location",
    "Please fill in all required fields (Area, Street, Building, Phone)": "Please fill in all required fields (Area, Street, Building, Phone)",
    "Profile": "Profile",
    "Farm Admin": "Farm Admin",
    "Payment Settings": "Payment Settings",
    "InstaPay Number": "InstaPay Number",
    "Social Media & Contact": "Social Media & Contact",
    "Content Management": "Content Management",
    "About Us": "About Us",
    "Write about your farm here...": "Write about your farm here...",
    "Delivery Policy": "Delivery Policy",
    "Explain your delivery policy...": "Explain your delivery policy...",
    "Save Changes": "Save Changes",
    "Settings updated successfully": "Settings updated successfully",
    "Offer Description": "Offer Description",
    "Image URL": "Image URL",
    "Discount %": "Discount %",
    "Active Offer": "Active Offer",
    "Create Offer": "Create Offer",
    "Offer created successfully": "Offer created successfully",
    "No offers yet": "No offers yet",
    "Inactive": "Inactive",
    "Successfully deleted": "Successfully deleted"
};

const ar = {
    "Brand Name": "فريندز فارم",
    "Shop Now": "تسوق الآن",
    "Categories": "الأقسام",
    "Explore Our Sections": "استكشف أقسامنا",
    "All": "الكل",
    "Featured Products": "مختاراتنا لك",
    "All Products": "كل المنتجات",
    "Fast Delivery": "توصيل سريع",
    "Home Raised": "تربية بيتي",
    "High Quality": "جودة عالية",
    "Add to Cart": "أضف للسلة",
    "EGP": "ج.م",
    "Login": "دخول",
    "Admin": "الإدارة",
    "Loading Farm": "جارٍ تحميل المزرعة",
    "Welcome Message": "مرحباً بك في فريندز فارم",
    "Hero Slogan": "أجود أنواع الفراخ والطيور الطازجة - توصيل سريع لباب بيتك",
    "Cart": "سلة المشتريات",
    "Empty Cart": "سلة المشتريات فارغة",
    "Total": "الإجمالي",
    "Checkout": "إتمام الطلب",
    "Remove": "حذف",
    "Products": "منتج",
    "Continue with Google": "المتابعة باستخدام جوجل",
    "Secure Login Message": "سجل دخولك بأمان عبر جوجل لإدارة طلباتك من المزرعة",
    "All Rights Reserved": "جميع الحقوق محفوظة",
    "Developed by": "تم التطوير بواسطة عبدالله سيد",
    "Fresh from the farm": "أجود أنواع الطيور والدواجن طازجة من المزرعة إليك مباشرة.",
    "Delivery Policy": "سياسة التوصيل",
    "About Farm": "عن المزرعة",
    "Within 24 hours": "خلال ٢٤ ساعة",
    "No hormones or additives": "بدون هرمونات أو إضافات",
    "Slaughtered according to Sharia": "ذبح حسب الشريعة الإسلامية",
    "Fresh chicken and birds of the highest quality": "فراخ وطيور طازجة بأعلى جودة",
    "Best selection of fresh poultry": "أجود أنواع الفراخ والطيور الطازجة - توصيل سريع لباب بيتك",
    "Email": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Sign In": "تسجيل الدخول",
    "Sign Up": "إنشاء حساب",
    "Register": "تسجيل",
    "Don't have an account?": "ليس لديك حساب؟",
    "Already have an account?": "لديك حساب بالفعل؟",
    "Forgot Password?": "نسيت كلمة المرور؟",
    "Full Name": "الاسم الكامل",
    "Create Account": "إنشاء حساب جديد",
    "Logout": "تسجيل الخروج",
    "Dashboard Summary": "نظرة عامة على أداء المزرعة",
    "Total Revenue": "إجمالي الإيرادات",
    "Monthly Revenue": "الإيرادات الشهرية",
    "Pending Orders": "طلبات قيد الانتظار",
    "Total Customers": "إجمالي العملاء",
    "Recent Orders": "أحدث الطلبات",
    "Top Performing Products": "الأكثر مبيعاً",
    "Lifetime Earnings": "أرباح الفترة كاملة",
    "Last 30 Days": "آخر ٣٠ يوم",
    "Awaiting Delivery": "في انتظار التوصيل",
    "Active Accounts": "حسابات نشطة",
    "Guest": "زائر",
    "Expenses": "المصاريف",
    "Overview": "نظرة عامة",
    "Orders": "الطلبات",
    "Users": "المستخدمين",
    "Settings": "الإعدادات",
    "Category Name": "اسم القسم",
    "Category Name (Arabic)": "اسم القسم (بالعربية)",
    "Category Image": "صورة القسم",
    "Add New Category": "إضافة قسم جديد",
    "Manage product sections": "إدارة أقسام المنتجات",
    "Date": "التاريخ",
    "Action": "إجراء",
    "Name (EN)": "الاسم (إنجليزي)",
    "Name (AR)": "الاسم (عربي)",
    "Image": "الصورة",
    "Are you sure?": "هل أنت متأكد؟",
    "This action cannot be undone.": "لا يمكن التراجع عن هذا الإجراء.",
    "Cancel": "إلغاء",
    "Continue": "متابعة",
    "Successfully deleted": "تم الحذف بنجاح",
    "Something went wrong": "حدث خطأ ما",
    "Create": "إنشاء",
    "Save Changes": "حفظ التغييرات",
    "Price": "السعر",
    "Category": "القسم",
    "Stock": "المخزون",
    "Featured": "مميز",
    "Active": "تفعيل",
    "items": "عناصر",
    "Loading...": "جارٍ التحميل...",
    "Edit Product": "تعديل المنتج",
    "Add New Product": "إضافة منتج جديد",
    "Product Name": "اسم المنتج",
    "Product Name (Arabic)": "اسم المنتج (بالعربية)",
    "Description": "الوصف",
    "Description (Arabic)": "الوصف (بالعربية)",
    "Product Image": "صورة المنتج",
    "Featured Product": "منتج مميز",
    "Featured Description": "سيظهر هذا المنتج في الصفحة الرئيسية",
    "Available Product": "منتج متاح",
    "Available Description": "سيكون هذا المنتج مرئياً في المتجر",
    "Order ID": "رقم الطلب",
    "Customer": "العميل",
    "Phone": "الهاتف",
    "Address": "العنوان",
    "Status": "الحالة",
    "Total Price": "الإجمالي",
    "Manage Orders": "إدارة الطلبات",
    "Manage Users": "إدارة المستخدمين",
    "Name": "الاسم",
    "Role": "الصلاحية",
    "Actions": "الإجراءات",
    "My Account": "حسابي",
    "Please login to checkout": "يرجى تسجيل الدخول لإتمام الطلب",
    "Order placed successfully!": "تم إرسال طلبك بنجاح!",
    "Account created successfully!": "تم إنشاء الحساب بنجاح!",
    "Account created! Please login.": "تم إنشاء الحساب! يرجى تسجيل الدخول.",
    "Registration failed": "فشل التسجيل",
    "Filters": "الفلاتر",
    "All Categories": "كل الأقسام",
    "Sort By": "ترتيب حسب",
    "Default": "الافتراضي",
    "Price: Low to High": "السعر: من الأقل للأعلى",
    "Price: High to Low": "السعر: من الأعلى للأقل",
    "Newest First": "الأحدث أولاً",
    "Clear": "مسح",
    "No products found": "لا توجد منتجات",
    "Customer Reviews": "آراء العملاء",
    "What Our Customers Say": "ماذا يقول عملاؤنا",
    "Verified Customer": "عميل موثق",
    "Special Offers": "عروض خاصة",
    "Don't Miss Out!": "لا تفوت الفرصة!",
    "OFF": "خصم",
    "Top Rated": "الأعلى تقييماً",
    "Our Picks For You": "مختاراتنا لك",
    "Admin Dashboard": "لوحة التحكم",
    "Sales Overview": "نظرة عامة على المبيعات",
    "Monthly Revenue Tracking": "تتبع الإيرادات الشهرية",
    "Finance Hub": "مركز المالية",
    "Net Profit vs Expenses": "صافي الربح مقابل المصاريف",
    "Net Profit": "صافي الربح",
    "Offers": "العروض",
    "Manage Offers": "إدارة العروض",
    "Add New Offer": "إضافة عرض جديد",
    "Offer Title": "عنوان العرض",
    "Discount Percentage": "نسبة الخصم",
    "Offer Price": "سعر العرض",
    "Original Price": "السعر الأصلي",
    "Testimonials": "آراء العملاء",
    "Manage Testimonials": "إدارة آراء العملاء",
    "Approved": "موافق عليه",
    "Pending Approval": "في انتظار الموافقة",
    "Approve": "موافقة",
    "Reject": "رفض",
    "Error": "خطأ",
    "Columns": "الأعمدة",
    "No results.": "لا توجد نتائج.",
    "Previous": "السابق",
    "Next": "التالي",
    "Filter...": "تصفية...",
    "Select All": "تحديد الكل",
    "name": "الاسم",
    "name_ar": "الاسم (عربي)",
    "price": "السعر",
    "category": "القسم",
    "createdAt": "تاريخ الإنشاء",
    "isFeatured": "مميز",
    "isArchived": "مؤرشف",
    "Area / Region": "المنطقة",
    "Street Name": "اسم الشارع",
    "Building No": "رقم المبنى",
    "Floor No": "رقم الدور",
    "Apartment No": "رقم الشقة",
    "Location Added ✓": "تم إضافة الموقع ✓",
    "Share My Current Location": "مشاركة موقعي الحالي",
    "Please fill in all required fields (Area, Street, Building, Phone)": "يرجى ملء جميع البيانات المطلوبة (المنطقة، الشارع، المبنى، الهاتف)",
    "Profile": "الملف الشخصي",
    "Farm Admin": "لوحة الإدارة",
    "Payment Settings": "إعدادات الدفع",
    "InstaPay Number": "رقم انستا باي",
    "Social Media & Contact": "التواصل الاجتماعي",
    "Content Management": "إدارة المحتوى",
    "About Us": "من نحن",
    "Write about your farm here...": "اكتب نبذة عن المزرعة هنا...",
    "Delivery Policy": "سياسة التوصيل",
    "Explain your delivery policy...": "اشرح سياسة التوصيل...",
    "Save Changes": "حفظ التغييرات",
    "Settings updated successfully": "تم تحديث الإعدادات بنجاح",
    "Offer Description": "وصف العرض",
    "Image URL": "رابط الصورة",
    "Discount %": "نسبة الخصم %",
    "Active Offer": "عرض نشط",
    "Create Offer": "إنشاء عرض",
    "Offer created successfully": "تم إنشاء العرض بنجاح",
    "No offers yet": "لا توجد عروض",
    "Inactive": "غير نشط",
    "Successfully deleted": "تم الحذف بنجاح"
};

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('ar');

    useEffect(() => {
        const saved = localStorage.getItem('language') as Language;
        if (saved) setLanguage(saved);
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    };

    const t = (key: string) => {
        const dict = language === 'ar' ? ar : en;
        return (dict as any)[key] || key;
    };

    const isRtl = language === 'ar';

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRtl }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
